//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataTrans
{
    using System;
    using System.Collections.Generic;
    
    public partial class ceremonyfee
    {
        public int serialid { get; set; }
        public Nullable<int> trial_CEREMONYID_2 { get; set; }
        public Nullable<int> feemoney { get; set; }
        public Nullable<int> advancemoney { get; set; }
        public string status { get; set; }
        public string family { get; set; }
        public string die1 { get; set; }
        public string trial_DIE2_8 { get; set; }
        public string die3 { get; set; }
        public string trial_LIVE1_10 { get; set; }
        public string trial_LIVE2_11 { get; set; }
        public string trial_LIVE3_12 { get; set; }
        public string phone { get; set; }
        public string address { get; set; }
        public string ps { get; set; }
        public string makeuser { get; set; }
        public string makedate { get; set; }
    }
}
