//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ceremony.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Believers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Believers()
        {
            this.Signups = new HashSet<Signups>();
        }
    
        public System.Guid BelieverID { get; set; }
        public int EmployeeType { get; set; }
        public string HallName { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public Nullable<int> MailZipcodeID { get; set; }
        public string MailZipcode { get; set; }
        public string MailAddress { get; set; }
        public Nullable<int> TextZipcodeID { get; set; }
        public string TextZipcode { get; set; }
        public string TextAddress { get; set; }
        public string LivingNameOne { get; set; }
        public string LivingNameTwo { get; set; }
        public string LivingNameThree { get; set; }
        public string LivingNameFour { get; set; }
        public string LivingNameFive { get; set; }
        public string LivingNameSix { get; set; }
        public string DeadNameOne { get; set; }
        public string DeadNameTwo { get; set; }
        public string DeadNameThree { get; set; }
        public string DeadNameFour { get; set; }
        public string DeadNameFive { get; set; }
        public string DeadNameSix { get; set; }
        public bool IsFixedNumber { get; set; }
    
        public virtual Zipcodes Zipcodes { get; set; }
        public virtual Zipcodes Zipcodes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Signups> Signups { get; set; }
    }
}
