//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ceremony.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CeremonyCategorys
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CeremonyCategorys()
        {
            this.CeremonyCategorys1 = new HashSet<CeremonyCategorys>();
            this.Signups = new HashSet<Signups>();
            this.Signups1 = new HashSet<Signups>();
        }
    
        public System.Guid CeremonyCategoryID { get; set; }
        public string Title { get; set; }
        public Nullable<System.Guid> ParentID { get; set; }
        public int Sort { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CeremonyCategorys> CeremonyCategorys1 { get; set; }
        public virtual CeremonyCategorys CeremonyCategorys2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Signups> Signups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Signups> Signups1 { get; set; }
    }
}
