//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ceremony.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CeremonyEntities : DbContext
    {
        public CeremonyEntities()
            : base("name=CeremonyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admins> Admins { get; set; }
        public virtual DbSet<Believers> Believers { get; set; }
        public virtual DbSet<CeremonyCategorys> CeremonyCategorys { get; set; }
        public virtual DbSet<Zipcodes> Zipcodes { get; set; }
        public virtual DbSet<SignupLogs> SignupLogs { get; set; }
        public virtual DbSet<Signups> Signups { get; set; }
        public virtual DbSet<BelieverView> BelieverView { get; set; }
        public virtual DbSet<SignupView> SignupView { get; set; }
    }
}
