//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ceremony.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Signups
    {
        public System.Guid SignupID { get; set; }
        public int Year { get; set; }
        public System.Guid CeremonyCategoryID { get; set; }
        public Nullable<System.DateTime> CeremonyDate { get; set; }
        public int SignupType { get; set; }
        public Nullable<System.Guid> BelieverID { get; set; }
        public string NumberTitle { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<int> Fee { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string LivingNameOne { get; set; }
        public string LivingNameTwo { get; set; }
        public string LivingNameThree { get; set; }
        public string LivingNameFour { get; set; }
        public string LivingNameFive { get; set; }
        public string LivingNameSix { get; set; }
        public string DeadNameOne { get; set; }
        public string DeadNameTwo { get; set; }
        public string DeadNameThree { get; set; }
        public string DeadNameFour { get; set; }
        public string DeadNameFive { get; set; }
        public string DeadNameSix { get; set; }
        public Nullable<int> MailZipcodeID { get; set; }
        public string MailZipcode { get; set; }
        public string MailAddress { get; set; }
        public Nullable<int> TextZipcodeID { get; set; }
        public string TextZipcode { get; set; }
        public string TextAddress { get; set; }
        public string Remark { get; set; }
        public Nullable<int> PrepayYear { get; set; }
        public Nullable<System.Guid> PrepayCeremonyCategoryID { get; set; }
        public int AdminID { get; set; }
        public System.DateTime Createdate { get; set; }
    
        public virtual Believers Believers { get; set; }
        public virtual CeremonyCategorys CeremonyCategorys { get; set; }
        public virtual CeremonyCategorys CeremonyCategorys1 { get; set; }
        public virtual Zipcodes Zipcodes { get; set; }
        public virtual Zipcodes Zipcodes1 { get; set; }
    }
}
