//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ceremony.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SignupView
    {
        public System.Guid SignupID { get; set; }
        public Nullable<System.Guid> BelieverID { get; set; }
        public int Year { get; set; }
        public string CeremonyTitle { get; set; }
        public Nullable<int> CeremonySort { get; set; }
        public int SignupType { get; set; }
        public System.Guid CeremonyCategoryID { get; set; }
        public string NumberTitle { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<int> Fee { get; set; }
        public string Employee { get; set; }
        public string Name { get; set; }
        public string Remark { get; set; }
        public string HallName { get; set; }
        public string DeadNameOne { get; set; }
        public string DeadNameTwo { get; set; }
        public string DeadNameThree { get; set; }
        public string DeadNameFour { get; set; }
        public string DeadNameFive { get; set; }
        public string DeadNameSix { get; set; }
        public string LivingNameOne { get; set; }
        public string LivingNameTwo { get; set; }
        public string LivingNameThree { get; set; }
        public string LivingNameFour { get; set; }
        public string LivingNameFive { get; set; }
        public string LivingNameSix { get; set; }
        public Nullable<int> PrepayYear { get; set; }
        public Nullable<System.Guid> PrepayCeremonyCategoryID { get; set; }
        public string PrepayCeremonyTitle { get; set; }
        public string Phone { get; set; }
        public string MailZipcode { get; set; }
        public string MailCity { get; set; }
        public string MailZone { get; set; }
        public string MailAddress { get; set; }
        public string TextZipcode { get; set; }
        public string TextCity { get; set; }
        public string TextZone { get; set; }
        public string TextAddress { get; set; }
        public string AdminName { get; set; }
        public System.DateTime Createdate { get; set; }
        public Nullable<bool> IsFixedNumber { get; set; }
    }
}
